#!/bin/sh

exec 2>&1
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
realpath "$0"
set -ex
exec chpst -u "$USER":"$GROUP" supervisord --configuration web2py.conf
