#!/bin/sh -eux

realpath "$0"
cd "$(dirname "$0")"
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
cd "$HOME"
exec chpst -u "$USER":"$GROUP" supervisord --configuration web2py.conf
