name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ github.token }}
concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}/${{ github.job }}
jobs:
  latest:
    name: ${{ github.job }} ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  edge:
    env:
      DOCKER_FROM: lib.docker:edge
      DOCKER_PYTHON_VERSION: '3.10'
      INPUTS_TAG: edge
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  debian:
    env:
      DOCKER_FROM: lib.docker:debian
      INPUTS_DOCKERFILE: Dockerfile.debian
      INPUTS_TAG: debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  ubuntu:
    env:
      DOCKER_FROM: lib.docker:ubuntu
      INPUTS_DOCKERFILE: Dockerfile.debian
      INPUTS_TAG: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  oracle:
    needs: latest
    env:
      INPUTS_DOCKERFILE: Dockerfile.oracle
      INPUTS_TAG: oracle
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
