on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          password: ${{ github.token }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          event-type: oracle
          repository: ${{ matrix.repo }}
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
    strategy:
      matrix:
        repo:
          - ${{ github.actor }}/web2py.docker
